# Generated by Django 4.2.28 on 2026-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'Жаңа'), ('confirmed', 'Расталды'), ('in_transit', 'Жолда'), ('delivered', 'Жеткізілді'), ('cancelled', 'Бас тартылды')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
                'ordering': ['-created_at'],
            },
        ),
    ]
