# Generated by Django 4.2.28 on 2026-02-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cargo.cargotype', verbose_name='Жүк түрі'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Есептелген баға'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Салмақ (кг)'),
        ),
    ]
