# Generated by Django 4.2.29 on 2026-03-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_seed_cargo_type_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargotype',
            name='category',
            field=models.CharField(choices=[('mal', 'Мал'), ('tovar', 'Тауарлар'), ('other', 'Басқа')], default='tovar', max_length=20),
        ),
    ]
