# Generated by Django 4.2.29 on 2026-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_alter_cargotype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Аты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Байланыс хабарламасы',
                'verbose_name_plural': 'Байланыс хабарламалары',
                'ordering': ['-created_at'],
            },
        ),
    ]
